version: '3.4'

x-app-variables: &app-variables
  SECRET_KEY: ${SECRET_KEY}
  HOST_NAMES: ${HOST_NAMES}
  DEFAULT_DATABASE_BACKEND: postgresql
  POSTGRESQL_DB_NAME: ${POSTGRESQL_DB_NAME}
  POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
  POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
  POSTGRESQL_HOSTNAME: postgres
  POSTGRESQL_PORT: 5432
  DEFAULT_STORAGE_BACKEND: s3
  S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
  S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
  S3_STORAGE_BUCKET_NAME: ${S3_STORAGE_BUCKET_NAME}
  S3_QUERYSTRING_EXPIRE: 3600
  S3_ENCRYPTION: 'True'
  BROKER_URL: redis://redis:6379/0


services:

  redis:
    container_name: redis
    hostname: redis
    image: redis:alpine
    networks:
      - main
    ports:
      - "6379:6379"
    volumes:
      - 'redisdata:/data'
    restart: on-failure

  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    networks:
      - main
    ports:
      - "5432:5432"
    restart: on-failure
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  app:
    build: .
    command: sh -c "wait-for postgres:5432 && python manage.py collectstatic --no-input && python manage.py migrate && gunicorn logboard.wsgi -b 0.0.0.0:8000"
    container_name: app
    depends_on:
      - postgres
      - redis
    ports:
      - "8000:8000"
    expose:
      - "8000"
    hostname: app
    image: app-image
    environment:
      <<: *app-variables
    networks:
      - main
    restart: on-failure

  celery_worker:
    command: sh -c "wait-for redis:6379 && wait-for app:8000 -- celery -A logboard worker -l info"
    container_name: celery_worker
    depends_on:
      - app
      - postgres
      - redis
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    hostname: celery_worker
    image: app-image
    environment:
      <<: *app-variables
    networks:
      - main
    restart: on-failure

  celery_beat:
    command: sh -c "wait-for redis:6379 && wait-for app:8000 -- celery -A logboard beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    container_name: celery_beat
    depends_on:
      - app
      - postgres
      - redis
    hostname: celery_beat
    image: app-image
    environment:
      <<: *app-variables
    networks:
      - main
    restart: on-failure

networks:
  main:

volumes:
  postgresql-data:
  redisdata:
