# Generated by Django 3.0.4 on 2020-06-15 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon_provider_id', models.IntegerField(default=0)),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('redeemed', models.BooleanField(default=False)),
            ],
        ),
    ]
