# Generated by Django 3.0.4 on 2020-06-15 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_auto_20200615_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='redeemed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
