# Generated by Django 3.0.4 on 2020-06-15 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_auto_20200615_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='redeemed_time',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
