# Generated by Django 3.0.4 on 2020-06-15 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_providers', '0002_remove_couponprovider_expired'),
        ('shops', '0001_initial'),
        ('coupons', '0004_auto_20200615_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='coupon_provider_id',
        ),
        migrations.AddField(
            model_name='coupon',
            name='coupon_provider',
            field=models.ForeignKey(default='c24d3841-a915-46a3-8ba6-e350a662082b', on_delete=django.db.models.deletion.CASCADE, to='coupon_providers.CouponProvider'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coupon',
            name='redeemed_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shops.Shop'),
        ),
    ]
