# Generated by Django 3.0.4 on 2020-06-15 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_providers', '0002_remove_couponprovider_expired'),
        ('shops', '0001_initial'),
        ('coupons', '0005_auto_20200615_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='coupon_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='coupon_providers.CouponProvider'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='redeemed_shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to='shops.Shop'),
        ),
    ]
