# Generated by Django 3.0.4 on 2020-06-16 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_wallet', '0002_auto_20200616_0558'),
        ('shop_wallet', '0002_auto_20200616_0558'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='shop_wallet.ShopWallet', to_field='wallet_address'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='user_wallet.UserWallet', to_field='wallet_address'),
        ),
    ]
