# Generated by Django 3.0.4 on 2020-04-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200404_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
