# Generated by Django 3.0.4 on 2020-04-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_measurement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='image',
        ),
    ]
