# Generated by Django 3.0.4 on 2020-04-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_measurement_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='image',
            field=models.ImageField(default='mylog14-03.png', upload_to='custodian_pics'),
        ),
    ]
