# Generated by Django 3.0.4 on 2020-04-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_authcustodianhashes_lastchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='bodyTemperatureCRITICAL',
            field=models.FloatField(default=37.5),
        ),
        migrations.AddField(
            model_name='measurement',
            name='bodyTemperatureMIN',
            field=models.FloatField(default=35),
        ),
        migrations.AddField(
            model_name='measurement',
            name='bodyTemperatureMax',
            field=models.FloatField(default=43),
        ),
    ]
