# Generated by Django 3.0.4 on 2020-04-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200404_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='bodyTemperatureMax',
            new_name='bodyTemperatureMAX',
        ),
    ]
