# Generated by Django 3.0.4 on 2020-04-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20200409_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='userHash',
            field=models.SlugField(default='abcdefg', max_length=100),
        ),
    ]
