# Generated by Django 3.0.4 on 2020-04-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='bodyTemperature',
            field=models.FloatField(default=36.5),
        ),
    ]
