# Generated by Django 3.0.5 on 2020-04-09 13:42

import applications.archives.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank='false', null='false', upload_to=applications.archives.models.archive_object_key)),
                ('file_name', models.CharField(default='untitled_file', max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
            ],
        ),
    ]
