# Generated by Django 3.0.5 on 2020-04-10 08:44

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField(default=0)),
                ('identity', models.CharField(max_length=50)),
                ('content', jsonfield.fields.JSONField()),
            ],
        ),
    ]
