# Generated by Django 3.0.4 on 2020-04-10 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0003_records_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCustodianHashes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userHash', models.SlugField(default='12', max_length=100)),
                ('reviewStatus', models.IntegerField(default=0)),
                ('lastChange', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
