# Generated by Django 3.0.4 on 2020-04-10 18:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0004_authcustodianhashes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthCustodianHashes',
        ),
        migrations.AddField(
            model_name='records',
            name='lastChange',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='records',
            name='reviewStatus',
            field=models.IntegerField(default=0),
        ),
    ]
