# Generated by Django 3.0.4 on 2020-04-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0005_auto_20200410_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='lastChange',
            new_name='last_change',
        ),
        migrations.RenameField(
            model_name='records',
            old_name='reviewStatus',
            new_name='review_status',
        ),
    ]
