# Generated by Django 3.0.4 on 2020-04-10 18:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0007_auto_20200410_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='records',
            name='first_access',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
