# Generated by Django 3.0.8 on 2020-07-20 01:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_content', models.TextField()),
                ('transaction_hash', models.CharField(max_length=255)),
                ('transaction_hash_validated', models.CharField(default='pending', max_length=255)),
                ('content_hash_verified', models.CharField(default='pending', max_length=255)),
                ('content_parsed', models.CharField(default='pending', max_length=255)),
                ('template_name', models.CharField(max_length=255, null=True)),
                ('timestamp', models.DateTimeField(null=True)),
                ('proof', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('fields', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
            ],
        ),
    ]
