# Generated by Django 3.0.4 on 2020-07-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('data_hash', models.CharField(max_length=255)),
                ('transaction_hash', models.CharField(max_length=255)),
                ('transaction_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
