# Generated by Django 3.0.8 on 2020-07-17 23:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='content',
            new_name='raw_content',
        ),
        migrations.AddField(
            model_name='record',
            name='fields',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='record',
            name='proof',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='template_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
