# Generated by Django 3.0.4 on 2020-07-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_record_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='data',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='data_hash',
            new_name='content_hash',
        ),
        migrations.AddField(
            model_name='record',
            name='content_verified',
            field=models.BooleanField(default=False),
        ),
    ]
