# Generated by Django 3.0.8 on 2020-07-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200717_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='record',
            name='content_verified',
        ),
        migrations.RemoveField(
            model_name='record',
            name='transaction_verified',
        ),
        migrations.AddField(
            model_name='record',
            name='content_hash_verified',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AddField(
            model_name='record',
            name='transaction_hash_validated',
            field=models.CharField(default='pending', max_length=255),
        ),
        migrations.AlterField(
            model_name='record',
            name='content_parsed',
            field=models.CharField(default='pending', max_length=255),
        ),
    ]
