# Generated by Django 3.0.8 on 2020-08-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_auto_20200806_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='transaction_hash',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
