# Generated by Django 3.0.8 on 2020-08-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20200811_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
