# Generated by Django 3.0.8 on 2020-08-28 11:51

import apps.records.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_record_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.records.models.upload_photo_path),
        ),
        migrations.AlterField(
            model_name='record',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=apps.records.models.upload_thumbnail_path),
        ),
    ]
