# Generated by Django 3.0.4 on 2020-04-04 09:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userHash', models.SlugField(default='test_hash', max_length=100)),
                ('bodyTemperatureUnit', models.CharField(choices=[('C', 'C'), ('F', 'F')], default='C', max_length=1)),
                ('coughing', models.IntegerField(default=0)),
                ('headache', models.IntegerField(default=0)),
                ('runnyNose', models.IntegerField(default=0)),
                ('soreThroat', models.IntegerField(default=0)),
                ('tasteLoss', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('accuracy', models.FloatField(default=0.0)),
            ],
        ),
    ]
