# Generated by Django 3.0.4 on 2020-04-04 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200404_1059'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Measurements',
            new_name='Measurement',
        ),
    ]
