# Generated by Django 3.0.4 on 2020-04-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20200404_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
