# Generated by Django 3.0.4 on 2020-04-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200404_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='bodyTemperatureMAX',
            field=models.FloatField(default=42),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='image',
            field=models.ImageField(default='/media/custodian_pics/mylog14-03_YSaAO0C.png', upload_to='media/custodian_pics'),
        ),
    ]
