# Generated by Django 3.0.4 on 2020-07-15 20:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=uuid.UUID('56d90a23-33dc-4deb-81a5-3d5b4cd6cd02'), max_length=150, unique=True),
        ),
    ]
