# Generated by Django 3.0.4 on 2020-07-15 23:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200715_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=150, primary_key=True, serialize=False),
        ),
    ]
