# Generated by Django 3.0.4 on 2020-06-15 19:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('discount', models.IntegerField(default=20)),
                ('quantity', models.IntegerField()),
                ('expiration_time', models.DateTimeField()),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
