# Generated by Django 3.0.4 on 2020-06-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon_providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponprovider',
            name='expired',
        ),
    ]
