# Generated by Django 3.0.8 on 2020-07-16 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mylog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mylog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mylogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mylog',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mylog', to='records.Record'),
        ),
    ]
