# Generated by Django 3.0.4 on 2020-06-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userwallet',
            name='accumulated_redeem_balance',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='current_balance',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
